Help the user understand why HTTP fails
Perl-Toolchain-Gang/HTTP-Tiny pull request #4
Opened 2023-08-06 20:29 UTC by briandfoy

I ran into a hiccup where something using HTTP::Tiny found a wrong SSL_CERT_FILE environment variable I had. After setting up a new machine with the latest OpenSSL, that file ended up under a different prefix without updating the environment. 

HTTP::Tiny can do more to track down this sort of error.

First, in the docs that lay out how HTTP::Tiny finds the cert file, it missed the first step (SSL_options), and also didn't say that a defined but missing SSL_CERT_FILE would stop the process. I fixed that.

I also improved the error message a little so people will know in which step HTTP::Tiny failed.

I don't particularly cared about how I typed it out, so change it as appropriate for whatever other concerns you have.

Some previous threads (chansen/p5-http-tiny#151, chansen/p5-http-tiny#152, metacpan/metacpan-client#121, metacpan/metacpan-client#82)

2023-10-11 02:48 UTC, briandfoy commented
If no one wants to act on this PR, I'll close it.

2023-10-13 13:20 UTC, abraxxa requested changes

2023-10-13 13:20 UTC, abraxxa commented on lib/HTTP/Tiny.pm
> +See L</TLS/SSL SUPPORT> for more on the C<verify_SSL> and C<SSL_options> attributes.
👍🏻 on using TLS and burrying the dead SSL!

2023-10-13 13:20 UTC, abraxxa commented on lib/HTTP/Tiny.pm
> +            die qq/'$ca_file' from $ca_file->[0] not found or not readable\n/;
I'd prefer either using to scalar variables for the CA file source for the message and its path+filename OR a hashref with descriptive key names, e.g. ca_file_source and ca_file.

2023-10-13 13:20 UTC, abraxxa commented on lib/HTTP/Tiny.pm
> +value, HTT::Tiny uses that. If the file is not readable, HTTP::Tiny fails and does
typo: HTT::Tiny -> HTTP::Tiny.

2023-10-13 13:20 UTC, abraxxa commented on lib/HTTP/Tiny.pm
> +* L<Mozilla::CA> - Validate SSL certificates when you don't have another source of a Certificate Authority cert
I'd use the wording "don´t have another source of trusted Certificate Authority certificates".

2024-07-04 21:20 UTC, abraxxa commented
Can we get these improvements merged? 🙏🏻

2024-07-09 15:57 UTC, briandfoy commented
It's been awhile, so here's the patch file in case I delete my fork. Typically, I don't let these things linger because it makes a mess of the things I have to track.

[http-tiny-4.patch](https://github.com/user-attachments/files/16146053/http-tiny-4.patch)

2024-07-09 15:59 UTC, closed without merging